### ISSUE TITLE
Check song volume

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#190]
It randomly turn to 100% when the bot change song

**Comment by LoryPelli** [comment]
If you skip a song, the volume of the next song will be 100% also if the server volume it's set to 15%

**Comment by LoryPelli** [comment]
> If you skip a song, the volume of the next song will be 100% also if the server volume it's set to 15%

Also if the bot switch to the next song, this happens (at least I tried if the song is looped)

**Comment by LoryPelli** [comment]
This bug is strange, I don't know what cause it and I don't think it's simple to fix because it doesn't happens everytime

**Comment by LoryPelli** [comment]
Again, the song volume went randomly to 100%

**Comment by LoryPelli** [comment]
![image](https://user-images.githubusercontent.com/87276663/188259946-c6a1b84c-593e-4b40-ab46-86510553c3c1.png)
Are you sure?

**Comment by LoryPelli** [comment]
I need to set again to 15% also if the bot says it's 15%

**Comment by Tetracyl** [comment]
Please stop spamming each issue with thousands of comments basically saying the same thing. An issue usually includes a title and description that includes most of the information needed to reproduce the issue. I've gotten more than a dozen emails now because you keep spamming comments on issues.

https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
